/* Auto-generated by gen_freq_tables.js — DO NOT EDIT */
#ifndef FREQ_LUT_MAP_H
#define FREQ_LUT_MAP_H

#include "types.h"

/* AY/YM2149: bypass |psg_khz - 1750| <= 35 */
#define FREQ_LUT_HW_KHZ        1750u
#define FREQ_LUT_BYPASS_TOL     35u  /* 2% */
/* YM2203: bypass |psg_khz - 3500| <= 70 */
#define FREQ_LUT_HW_YM_KHZ     3500u
#define FREQ_LUT_BYPASS_TOL_YM  70u  /* 2% */

#define FREQ_LUT_AY_COUNT     6u
#define FREQ_LUT_YM_COUNT     5u
#define FREQ_LUT_ENTRIES      4096u   /* 12-bit PSG */
#define FREQ_LUT_FM_MAX       2048u  /* 11-bit FM F-Number */
#define FREQ_LUT_BYTES        8192u     /* per table */

typedef struct {
    uint16_t clk_khz;   /* canonical PSG clock in kHz  */
    uint16_t tol_khz;   /* ±tolerance in kHz (5%)      */
    uint8_t  page;      /* plugin page (PAGE_BASE-based) */
    uint16_t offset;    /* byte offset within page     */
} freq_lut_entry_t;

/* AY/YM2149 table map (tolerance = 5% of canonical PSG clock) */
static const freq_lut_entry_t freq_lut_map_ay[FREQ_LUT_AY_COUNT] = {
    { 1790u,  90u, 1, 0x0000 },  /* NTSC_1790 */
    { 1500u,  75u, 1, 0x2000 },  /* 3MHz_1500 */
    { 2000u, 100u, 2, 0x0000 },  /* 4MHz_2000 */
    { 1000u,  50u, 2, 0x2000 },  /* CPC_1000 */
    { 1250u,  63u, 3, 0x0000 },  /* 1250 */
    {  750u,  38u, 3, 0x2000 }   /* 1500_750 */
};

/* YM2203 table map (full master clock, same tables as AY) */
static const freq_lut_entry_t freq_lut_map_ym[FREQ_LUT_YM_COUNT] = {
    { 3580u, 179u, 1, 0x0000 },  /* NTSC_1790 (YM2203@3580kHz) */
    { 3000u, 150u, 1, 0x2000 },  /* 3MHz_1500 (YM2203@3000kHz) */
    { 4000u, 200u, 2, 0x0000 },  /* 4MHz_2000 (YM2203@4000kHz) */
    { 2500u, 125u, 3, 0x0000 },  /* 1250 (YM2203@2500kHz) */
    { 1500u,  75u, 3, 0x2000 }   /* 1500_750 (YM2203@1500kHz) */
};

/*
 * Usage in vgm.c (parse_header):
 *
 *   uint16_t psg_khz = chip_clock / 1000;  // already have clock_khz
 *
 *   // 1. Bypass check
 *   uint16_t diff = (psg_khz > FREQ_LUT_HW_KHZ)
 *                  ? psg_khz - FREQ_LUT_HW_KHZ
 *                  : FREQ_LUT_HW_KHZ - psg_khz;
 *   if (diff <= FREQ_LUT_BYPASS_TOL) → no scaling needed
 *
 *   // 2. Find matching table (linear scan, 5 entries)
 *   for (i = 0; i < FREQ_LUT_COUNT; i++) {
 *       diff = abs16(psg_khz - freq_lut_map[i].clk_khz);
 *       if (diff <= freq_lut_map[i].tol_khz) {
 *           wc_mng0_pl(freq_lut_map[i].page);
 *           lut_base = (uint16_t *)freq_lut_map[i].offset;
 *           break;
 *       }
 *   }
 *
 *   // 3. No match → runtime generate into page 1
 *
 *   // Access: scaled_period = lut_base[original_period]
 *   //   PSG: full 12-bit index (0..4095)
 *   //   FM:  11-bit F-Number index (0..2047)
 */

#endif /* FREQ_LUT_MAP_H */
